# Site settings
title: bangiebangs
email: bangie@bangiebangs.com
description: > # this means to ignore newlines until "baseurl:"
  this is where i play around with jekyll & git -- enjoy the chaos. might contain posts on stuff i do (queer stuff, crafts, hacking, events, organizing, berlin, greece, rescuing dogs). 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bangiebangs
github_username:  bangiebangs

# Build settings
markdown: kramdown
